#! /bin/sh
\lf -server &

rm /home/kyle/.xsession-errors &
rm /home/kyle/.mozilla &
rm /home/kyle/screen-recording.mp4 &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width           6
bspc config window_gap             14
bspc config top_padding            10
bspc config bottom_padding         10
bspc config left_padding           10
bspc config right_padding          10

bspc config left_monocle_padding   25
bspc config right_monocle_padding  25
bspc config top_monocle_padding    25
bspc config bottom_monocle_padding 25

bspc config split_ratio            0.55
#bspc config borderless_monocle    true
#bspc config gapless_monocle       true
bspc config pointer_follows_focus  true
bspc config focus_follows_pointer  true

bspc config focused_border_color   "#e35b15"
bspc config normal_border_color    "#1b110e"
bspc config active_border_color    "#f99666"
bspc config presel_feedback_color 	"#f99666"

bspc rule -a Zathura state=fullscreen
bspc rule -a Stremio desktop='^9' state=fullscreen follow=on
bspc rule -a ripdrag state=floating focus=on
bspc rule -a firefox desktop='^3' follow=on
bspc rule -a Cropgui state=floating focus=on

pidof picom -b --config $HOME/.config/picom/picom.conf || picom -b --config $HOME/.config/picom/picom.conf &
pidof dunst || /usr/bin/dunst &
xwallpaper --zoom ~/.config/wall.png &
nm-applet --indicator &
xsetroot -cursor_name left_ptr &
unclutter --timeout 1 &
pidof bspswallow || bspswallow &
remap &
pgrep -x sxhkd > /dev/null || sxhkd &
vivaldi-stable &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# scratch 
#st -c scratchterm &
#bspc rule -a scratchterm sticky=on state=floating hidden=on
